server:
  port: 8888

spring:
  application:
    name: configserver1
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xixincan/clouddemo.git
          search-paths: config
          username: xixincan
          password: xixincan0908
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
