server:
  port: 8766
spring:
  application:
    name: authorizationserver1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
