server:
  port: 8767
spring:
  application:
    name: authorizationresource1


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true