spring:
  profiles:
    active: eureka_la
  application:
    name: eureka-client-provider

server:
  port: 8760

eureka:
  instance:
    hostname: client
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    prefer-ip-address: true   # 是否将当前的 IP注册到Eureka Server
---
spring:
  profiles: eureka_la
eureka:
  client:
    service-url: # Eureka Server注册中心地址，用于client与server进行交流
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: eureka_ha
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/, http://localhost:8763/eureka/